#pragma once

#include <algorithm>
#include <utility>
#include <vector>
#include <functional>
#include <string>
#include <cstring>
#include <cassert>
#include <cerrno>
#include <iostream>
#include <thread>
#include <mutex>
#include <queue>
#include <atomic>
#include <condition_variable>
#include <memory>
#include <unordered_map>
#include <thread>
#include <future>
#include <variant>
#include <set>
#include <chrono>
#include <ratio>

#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/uio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/epoll.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <sys/eventfd.h>
#include <unistd.h>
#include <sys/timerfd.h>
